include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = FoundationWrapperC
FoundationWrapperC_OBJC_FILES = NSObject.wrap.m NSString.wrap.m
FoundationWrapperC_HEADER_FILES = NSObject.wrap.h NSString.wrap.h FoundationWrapperC.h
FoundationWrapperC_HEADER_FILES_INSTALL_DIR = FoundationWrapperC
FoundationWrapperC_NEEDS_GUI = yes

include $(GNUSTEP_MAKEFILES)/library.make
