// C interface to class NSString
unsigned char NSString_cls_print_noarg(id self);
unsigned char NSString_cls_printError_noarg(id self);
unsigned char NSString_cls_printLine_noarg(id self);
unsigned char NSString_cls_printErrorLine_noarg(id self);
id NSString_cls_plus_(id arg2, id self);
id NSString_cls_plus_plus_(id arg2, id arg3, id self);
id NSString_cls_plus_plus_plus_(id arg2, id arg3, id arg4, id self);
id NSString_cls_plus_plus_plus_plus_(id arg2, id arg3, id arg4, id arg5, id self);
id NSString_cls_plus_plus_plus_plus_plus_(id arg2, id arg3, id arg4, id arg5, id arg6, id self);
id NSString_cls_stringByDeletingPrefix_(id arg2, id self);
id NSString_cls_stringByDeletingSuffix_(id arg2, id self);
id NSString_cls_stringByTrimmingLeadSpaces_noarg(id self);
id NSString_cls_stringByTrimmingTailSpaces_noarg(id self);
id NSString_cls_stringByTrimmingSpaces_noarg(id self);
id NSString_cls_stringByReplacingString_withString_(id arg2, id arg3, id self);
id NSString_cls_substringFromRange_(struct _NSRange arg2, id self);
void NSString_cls_appendToXMLRPC_indent_for_(id arg2, unsigned long long arg3, id arg4, id self);
id NSString_cls_stringByEscapingXML_noarg(id self);
id NSString_cls_stringByUnescapingXML_noarg(id self);
id NSString_cls__stringByExpandingXMLEntities_noarg(id self);
id NSString_cls_stringByRepeatingCurrentString_(unsigned long long arg2, id self);
const char* NSString_cls_gnutlsFileSystemRepresentation_noarg(id self);
id NSString_cls__unicodeString_noarg(id self);
id NSString_cls__normalizedICUStringOfType_mode_(const char* arg2, signed int arg3, id self);
id NSString_cls_init_noarg(id self);
id NSString_cls_initWithBytes_length_encoding_(void* const arg2, unsigned long long arg3, signed int arg4, id self);
id NSString_cls_initWithBytesNoCopy_length_encoding_freeWhenDone_(void* arg2, unsigned long long arg3, signed int arg4, unsigned char arg5, id self);
id NSString_cls_initWithCharactersNoCopy_length_freeWhenDone_(unsigned short* arg2, unsigned long long arg3, unsigned char arg4, id self);
id NSString_cls_initWithCharacters_length_(unsigned short* const arg2, unsigned long long arg3, id self);
id NSString_cls_initWithCStringNoCopy_length_freeWhenDone_(char* arg2, unsigned long long arg3, unsigned char arg4, id self);
id NSString_cls_initWithCString_encoding_(const char* arg2, signed int arg3, id self);
id NSString_cls_initWithCString_length_(const char* arg2, unsigned long long arg3, id self);
id NSString_cls_initWithCString_(const char* arg2, id self);
id NSString_cls_initWithString_(id arg2, id self);
id NSString_cls_initWithUTF8String_(const char* arg2, id self);
id NSString_cls_initWithFormat_(id arg2, id self);
id NSString_cls_initWithFormat_locale_(id arg2, id arg3, id self);
// id NSString_cls_initWithFormat_arguments_(id arg2, va_list arg3, id self);
// id NSString_cls_initWithFormat_locale_arguments_(id arg2, id arg3, va_list arg4, id self);
id NSString_cls_initWithData_encoding_(id arg2, signed int arg3, id self);
id NSString_cls_initWithContentsOfFile_(id arg2, id self);
id NSString_cls_initWithContentsOfFile_usedEncoding_error_(id arg2, signed int* arg3, id* arg4, id self);
id NSString_cls_initWithContentsOfFile_encoding_error_(id arg2, signed int arg3, id* arg4, id self);
id NSString_cls_initWithContentsOfURL_(id arg2, id self);
id NSString_cls_initWithContentsOfURL_usedEncoding_error_(id arg2, signed int* arg3, id* arg4, id self);
id NSString_cls_initWithContentsOfURL_encoding_error_(id arg2, signed int arg3, id* arg4, id self);
unsigned long long NSString_cls_length_noarg(id self);
unsigned short NSString_cls_characterAtIndex_(unsigned long long arg2, id self);
id NSString_cls_decomposedStringWithCompatibilityMapping_noarg(id self);
id NSString_cls_decomposedStringWithCanonicalMapping_noarg(id self);
void NSString_cls_getCharacters_(unsigned short* arg2, id self);
void NSString_cls_getCharacters_range_(unsigned short* arg2, struct _NSRange arg3, id self);
id NSString_cls_stringByAddingPercentEncodingWithAllowedCharacters_(id arg2, id self);
id NSString_cls_stringByRemovingPercentEncoding_noarg(id self);
id NSString_cls_stringByAddingPercentEscapesUsingEncoding_(signed int arg2, id self);
id NSString_cls_stringByAppendingFormat_(id arg2, id self);
id NSString_cls_stringByAppendingString_(id arg2, id self);
id NSString_cls_componentsSeparatedByCharactersInSet_(id arg2, id self);
id NSString_cls_componentsSeparatedByString_(id arg2, id self);
id NSString_cls_stringByReplacingOccurrencesOfString_withString_options_range_(id arg2, id arg3, unsigned long long arg4, struct _NSRange arg5, id self);
id NSString_cls_stringByReplacingOccurrencesOfString_withString_(id arg2, id arg3, id self);
id NSString_cls_stringByReplacingCharactersInRange_withString_(struct _NSRange arg2, id arg3, id self);
id NSString_cls_substringFromIndex_(unsigned long long arg2, id self);
id NSString_cls_substringToIndex_(unsigned long long arg2, id self);
// id NSString_cls_substringFromRange_(struct _NSRange arg2, id self);
id NSString_cls_substringWithRange_(struct _NSRange arg2, id self);
struct _NSRange NSString_cls_rangeOfCharacterFromSet_(id arg2, id self);
struct _NSRange NSString_cls_rangeOfCharacterFromSet_options_(id arg2, unsigned long long arg3, id self);
struct _NSRange NSString_cls_rangeOfCharacterFromSet_options_range_(id arg2, unsigned long long arg3, struct _NSRange arg4, id self);
struct _NSRange NSString_cls_rangeOfString_(id arg2, id self);
struct _NSRange NSString_cls_rangeOfString_options_(id arg2, unsigned long long arg3, id self);
struct _NSRange NSString_cls_rangeOfString_options_range_(id arg2, unsigned long long arg3, struct _NSRange arg4, id self);
struct _NSRange NSString_cls_rangeOfString_options_range_locale_(id arg2, unsigned long long arg3, struct _NSRange arg4, id arg5, id self);
unsigned long long NSString_cls_indexOfString_(id arg2, id self);
unsigned long long NSString_cls_indexOfString_fromIndex_(id arg2, unsigned long long arg3, id self);
struct _NSRange NSString_cls_rangeOfComposedCharacterSequenceAtIndex_(unsigned long long arg2, id self);
struct _NSRange NSString_cls_rangeOfComposedCharacterSequencesForRange_(struct _NSRange arg2, id self);
signed long long NSString_cls_compare_(id arg2, id self);
signed long long NSString_cls_compare_options_(id arg2, unsigned long long arg3, id self);
signed long long NSString_cls_compare_options_range_(id arg2, unsigned long long arg3, struct _NSRange arg4, id self);
unsigned char NSString_cls_hasPrefix_(id arg2, id self);
unsigned char NSString_cls_hasSuffix_(id arg2, id self);
unsigned char NSString_cls_isEqual_(id arg2, id self);
unsigned char NSString_cls_isEqualToString_(id arg2, id self);
unsigned long long NSString_cls_hash_noarg(id self);
id NSString_cls_commonPrefixWithString_options_(id arg2, unsigned long long arg3, id self);
struct _NSRange NSString_cls_lineRangeForRange_(struct _NSRange arg2, id self);
void NSString_cls__getStart_end_contentsEnd_forRange_lineSep_(unsigned long long* arg2, unsigned long long* arg3, unsigned long long* arg4, struct _NSRange arg5, unsigned char arg6, id self);
void NSString_cls_getLineStart_end_contentsEnd_forRange_(unsigned long long* arg2, unsigned long long* arg3, unsigned long long* arg4, struct _NSRange arg5, id self);
void NSString_cls_getParagraphStart_end_contentsEnd_forRange_(unsigned long long* arg2, unsigned long long* arg3, unsigned long long* arg4, struct _NSRange arg5, id self);
id NSString_cls_capitalizedString_noarg(id self);
id NSString_cls_lowercaseString_noarg(id self);
id NSString_cls_uppercaseString_noarg(id self);
id NSString_cls_description_noarg(id self);
unsigned short* const NSString_cls_unicharString_noarg(id self);
const char* NSString_cls_cString_noarg(id self);
const char* NSString_cls_cStringUsingEncoding_(signed int arg2, id self);
unsigned long long NSString_cls_lengthOfBytesUsingEncoding_(signed int arg2, id self);
unsigned long long NSString_cls_maximumLengthOfBytesUsingEncoding_(signed int arg2, id self);
const char* NSString_cls_lossyCString_noarg(id self);
const char* NSString_cls_UTF8String_noarg(id self);
unsigned long long NSString_cls_cStringLength_noarg(id self);
void NSString_cls_getCString_(char* arg2, id self);
void NSString_cls_getCString_maxLength_(char* arg2, unsigned long long arg3, id self);
unsigned char NSString_cls_getCString_maxLength_encoding_(char* arg2, unsigned long long arg3, signed int arg4, id self);
void NSString_cls_getCString_maxLength_range_remainingRange_(char* arg2, unsigned long long arg3, struct _NSRange arg4, struct _NSRange* arg5, id self);
unsigned char NSString_cls_boolValue_noarg(id self);
// struct AutoBindingsUnknown173561222 /* {?=cCCC[38C]} */ NSString_cls_decimalValue_noarg(id self);
double NSString_cls_doubleValue_noarg(id self);
float NSString_cls_floatValue_noarg(id self);
signed int NSString_cls_intValue_noarg(id self);
signed long long NSString_cls_integerValue_noarg(id self);
signed long long NSString_cls_longLongValue_noarg(id self);
unsigned char NSString_cls_canBeConvertedToEncoding_(signed int arg2, id self);
id NSString_cls_dataUsingEncoding_(signed int arg2, id self);
id NSString_cls_dataUsingEncoding_allowLossyConversion_(signed int arg2, unsigned char arg3, id self);
signed int NSString_cls_fastestEncoding_noarg(id self);
signed int NSString_cls_smallestEncoding_noarg(id self);
unsigned long long NSString_cls_completePathIntoString_caseSensitive_matchesIntoArray_filterTypes_(id* arg2, unsigned char arg3, id* arg4, id arg5, id self);
const char* NSString_cls_fileSystemRepresentation_noarg(id self);
unsigned char NSString_cls_getFileSystemRepresentation_maxLength_(char* arg2, unsigned long long arg3, id self);
id NSString_cls_lastPathComponent_noarg(id self);
struct _NSRange NSString_cls_paragraphRangeForRange_(struct _NSRange arg2, id self);
id NSString_cls_pathExtension_noarg(id self);
id NSString_cls_precomposedStringWithCompatibilityMapping_noarg(id self);
id NSString_cls_precomposedStringWithCanonicalMapping_noarg(id self);
id NSString_cls_stringByAppendingPathComponent_(id arg2, id self);
id NSString_cls_stringByAppendingPathExtension_(id arg2, id self);
id NSString_cls_stringByDeletingLastPathComponent_noarg(id self);
id NSString_cls_stringByDeletingPathExtension_noarg(id self);
id NSString_cls_stringByExpandingTildeInPath_noarg(id self);
id NSString_cls_stringByAbbreviatingWithTildeInPath_noarg(id self);
id NSString_cls_stringByPaddingToLength_withString_startingAtIndex_(unsigned long long arg2, id arg3, unsigned long long arg4, id self);
id NSString_cls_stringByReplacingPercentEscapesUsingEncoding_(signed int arg2, id self);
id NSString_cls_stringByResolvingSymlinksInPath_noarg(id self);
id NSString_cls_stringByStandardizingPath_noarg(id self);
id NSString_cls_stringByTrimmingCharactersInSet_(id arg2, id self);
signed int NSString_cls__baseLength_noarg(id self);
unsigned char NSString_cls_isAbsolutePath_noarg(id self);
id NSString_cls_pathComponents_noarg(id self);
id NSString_cls_stringsByAppendingPaths_(id arg2, id self);
signed long long NSString_cls_caseInsensitiveCompare_(id arg2, id self);
signed long long NSString_cls_compare_options_range_locale_(id arg2, unsigned long long arg3, struct _NSRange arg4, id arg5, id self);
signed long long NSString_cls_localizedCompare_(id arg2, id self);
signed long long NSString_cls_localizedCaseInsensitiveCompare_(id arg2, id self);
unsigned char NSString_cls_writeToFile_atomically_(id arg2, unsigned char arg3, id self);
unsigned char NSString_cls_writeToFile_atomically_encoding_error_(id arg2, unsigned char arg3, signed int arg4, id* arg5, id self);
unsigned char NSString_cls_writeToURL_atomically_encoding_error_(id arg2, unsigned char arg3, signed int arg4, id* arg5, id self);
unsigned char NSString_cls_writeToURL_atomically_(id arg2, unsigned char arg3, id self);
id NSString_cls_copyWithZone_(struct _NSZone* arg2, id self);
id NSString_cls_mutableCopyWithZone_(struct _NSZone* arg2, id self);
void NSString_cls_encodeWithCoder_(id arg2, id self);
id NSString_cls_initWithCoder_(id arg2, id self);
Class NSString_cls_classForCoder_noarg(id self);
id NSString_cls_replacementObjectForPortCoder_(id arg2, id self);
id NSString_cls_propertyList_noarg(id self);
id NSString_cls_propertyListFromStringsFileFormat_noarg(id self);
unsigned char NSString_cls_containsString_(id arg2, id self);
void NSString_cls_enumerateSubstringsInRange_options_usingBlock_(struct _NSRange arg2, unsigned long long arg3, id arg4, id self);

// id NSString_inst_stringWithFormat_arguments_(id arg2, va_list arg3, id self);
void NSString_inst_atExit_noarg(id self);
void NSString_inst_initialize_noarg(id self);
id NSString_inst_allocWithZone_(struct _NSZone* arg2, id self);
Class NSString_inst_constantStringClass_noarg(id self);
id NSString_inst_string_noarg(id self);
id NSString_inst_stringWithString_(id arg2, id self);
id NSString_inst_stringWithCharacters_length_(unsigned short* const arg2, unsigned long long arg3, id self);
id NSString_inst_stringWithCString_(const char* arg2, id self);
id NSString_inst_stringWithCString_encoding_(const char* arg2, signed int arg3, id self);
id NSString_inst_stringWithCString_length_(const char* arg2, unsigned long long arg3, id self);
id NSString_inst_stringWithUTF8String_(const char* arg2, id self);
id NSString_inst_stringWithContentsOfFile_(id arg2, id self);
id NSString_inst_stringWithContentsOfFile_usedEncoding_error_(id arg2, signed int* arg3, id* arg4, id self);
id NSString_inst_stringWithContentsOfFile_encoding_error_(id arg2, signed int arg3, id* arg4, id self);
id NSString_inst_stringWithContentsOfURL_(id arg2, id self);
id NSString_inst_stringWithContentsOfURL_usedEncoding_error_(id arg2, signed int* arg3, id* arg4, id self);
id NSString_inst_stringWithContentsOfURL_encoding_error_(id arg2, signed int arg3, id* arg4, id self);
id NSString_inst_stringWithFormat_(id arg2, id self);
signed int NSString_inst_defaultCStringEncoding_noarg(id self);
signed int* NSString_inst_availableStringEncodings_noarg(id self);
id NSString_inst_localizedNameOfStringEncoding_(signed int arg2, id self);
id NSString_inst_pathWithComponents_(id arg2, id self);
id NSString_inst_localizedStringWithFormat_(id arg2, id self);
// End C interface to class NSString
